# This is the default module. It is kept intentionally empty/noop as the
# real work should be done in the individual modules, which can easily be moved into their own google 
# projects one day if necessary
# version: v1

runtime: python27
api_version: 1
threadsafe: true

instance_class: B4 
basic_scaling:
  max_instances: 1
  idle_timeout: 1m 

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /.*
  script: noop.application


skip_files:
# Default files
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$

# IntelliJ/PyCharm files
- (.idea/.*)

# Temporary
- (old-src/*)

# These packages are either preinstalled or not needed on the actual deployed application  
- (venv/lib/python2.7/site-packages/appengine_sdk.*)
- (venv/lib/python2.7/site-packages/setuptools/.*)
- (venv/lib/python2.7/site-packages/nose.*)
- (venv/lib/python2.7/site-packages/pip.*)
- (venv/lib/python2.7/site-packages/pyasn.*)
